version: '3.8'

services:
  app:
    build: .
    container_name: faq_app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env  # Loads environment variables from a file
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/faqdb  # Connect to Mongo inside Docker
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "start"]

  mongodb:
    image: mongo:6.0
    container_name: faq_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    container_name: faq_redis
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
